import React from "react";
import "./privacyPolicy.css";
const PrivacyPolicy = () => {
  return (
    <>
      <div className="container">
        <div>
          <h4 className="text-center">Privacy Policy</h4>
          <p>
            This privacy policy (“Privacy Policy”) sets out how Hurix Systems
            Private Limited (“Company”) uses and protects any information that
            you give the Company when you use https://connect.hurixsystems.com/
            (collectively referred to as “Hurix Supplier Portal”). The Company
            is committed to protecting your privacy. This Privacy Policy
            explains how the Company collects, uses and shares your personal
            information. This Privacy Policy applies to your use of Hurix as
            further described in Hurix’s Terms and Conditions available at
            https://connect.hurixsystems.com/. By using Hurix, you agree to be
            bound by the terms and conditions of this Privacy Policy. You hereby
            expressly consent to the processing of your personal information in
            accordance with this Privacy Policy. Your personal information may
            be stored, processed or transmitted in India or any other part of
            the world, where laws regarding storing, processing or transmitting
            of personal information may be less restrictive than the laws in
            your country. If you do not agree to the terms of this Privacy
            Policy, please do not use or access Hurix. By mere use of or access
            to Hurix, you expressly consent to the Company’s use and disclosure
            of your personal information in accordance with this Privacy Policy.
            This Privacy Policy is incorporated into and subject to the Terms
            and Conditions.
          </p>
        </div>
        <div>
          <h5>
            <u>Acceptance</u>
          </h5>
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and the rules framed thereunder, as applicable
            and amended from time to time, pertaining to electronic records in
            various statutes as amended by the Information Technology Act, 2000.
            This electronic record is generated by a computer system and does
            not require any physical or digital signatures.
          </p>
        </div>
        <div>
          <h5>TYPES OF INFORMATION THE COMPANY COLLECTS</h5>
          <p>
            The Company collects personal information from you in a variety of
            ways when you use Hurix, such as:
          </p>
          <div>
            <h6 className="d-inline fst-italic">Account.</h6>
            <p className="d-inline">
              The Company collects, and associates with your account
              information, your name, your company's name, birth date, email
              address, phone number, profile details, work, gender, business
              details, address and other personally identifiable information. If
              you create an account by logging in with your credentials from
              your third party account with certain social networking sites
              (such as Twitter, LinkedIn, Google+ or Facebook), the Company may
              receive information about you from such social networking sites,
              in accordance with the terms of use and privacy policy of that
              social networking site. The Company works with such social
              networking site's application protocol interface (API) in a way
              that allows you to authorize the Company to access your account on
              that social networking site on your behalf. If you consent to the
              Company sharing your information with these social networking
              sites (e.g., post public content on your wall/profile page), the
              Company will share information with them in accordance with your
              privacy choices. Once the Company shares your information with
              these social networking sites, the terms and policies of these
              sites, and not this Privacy Policy, will apply to their use of
              your information.
            </p>
          </div>
          <div className="mt-2">
            <h6 className="d-inline fst-italic">
              Website and Software Use Related.
            </h6>
            <p className="d-inline">
              {" "}
              When you use Hurix, the Company stores, processes and transmits
              your files (like images, videos, emails, feedback, postings,
              comments, log file information from browser, software etc.,
              metadata and other data) and information related to them. If you
              give the Company access to your contacts, the Company will store
              those contacts on its servers for you to use. This will make it
              easy for you to do things like share your data, send emails, and
              invite others to use Hurix.{" "}
            </p>
          </div>
          <div className="mt-2">
            <h6 className="d-inline fst-italic">Usage.</h6>
            <p className="d-inline">
              The Company collects information about your business area,
              expertise and preferences as per the data input by you. Your
              devices (depending on their settings) may also transmit location
              information to the Company.
            </p>
          </div>
          <div className="mt-2">
            <h6 className="d-inline fst-italic">
              Cookies and other Technologies.{" "}
            </h6>
            <p className="d-inline">
              The Company may use technologies like cookies and pixel tags to
              provide, improve, protect and promote Hurix. For example, cookies
              help the Company with things like remembering your username for
              your next visit, understanding how you are interacting with Hurix,
              and improving it based on that information. The Company uses
              software tools to collect information about how you interact with
              Hurix, such as mouse clicks, touch gestures, drags, hover-overs,
              response times, errors, page views and length of visits to certain
              pages. You can set your browser to not accept cookies, but this
              may limit your ability to use Hurix. The Company may ask its other
              partners to serve ads or services to your computer systems or
              other devices, which may use cookies or similar technologies
              placed by the Company or the third party. The Company does not
              control use of such technologies used by advertisers and partners
              and it expressly disclaims responsibility for information
              collected through them.
            </p>
          </div>
          <div className="mt-2">
            <h6 className="d-inline fst-italic">Analytic Services. </h6>
            <p className="d-inline">
              The Company may use third party analytics services such as Google
              Analytics, KISSmetrics and / or Comscore, to collect information
              about how you use and interact with Hurix. Such third party
              analytics services may use cookies to gather information such as
              the pages you visited, your IP address, a date/time stamp for your
              visit and which website or hyperlink referred you to Hurix. The
              Company uses these analytics services to analyze how people use
              Hurix, to improve them, to customize the content/features users
              see/use based upon their interests and to send email to users who
              are not actively using Hurix. For more information about how these
              entities use this information, please refer to their privacy
              policies made available on their respective websites.
            </p>
          </div>
          <div className="mt-2">
            <h6 className="d-inline fst-italic">
              Information Collected from Third Parties.{" "}
            </h6>
            <p className="d-inline">
              The Company may receive information about you from third parties
              that offer hyperlinks to Hurix on their website and/or products
              and/or services. These third parties may supply the Company with
              your information. The Company may add this information to the
              information it has already collected from you via Hurix in order
              to improve the products and/or services of the Company and/or its
              website and software.
            </p>
          </div>
        </div>
        <div className="mt-3">
          <h5>
            <u>HOW THE COMPANY USES YOUR INFORMATION</u>
          </h5>
          <div>
            <h6 className="d-inline fst-italic">General Use. </h6>
            <p className="d-inline">
              In general, the information you submit to the Company is used
              either to respond to requests that you make, or to aid the Company
              in serving you better. The Company may use your information in the
              following ways:
            </p>
          </div>
          <div>
            <ul>
              <li>
                to send you a welcome e-mail and to verify ownership of the
                e-mail address provided when your user account was created.
              </li>
              <li>to identify you as a user in the Company's system</li>
              <li>to provide access to Hurix</li>
              <li>
                to facilitate the creation of and secure your user account
              </li>
              <li>to provide improved administration of Hurix</li>
              <li>to notify you about updates to Hurix</li>
              <li>
                to improve and customize the quality of experience when you
                interact with Hurix
              </li>
              <li>
                to send you administrative e-mail notifications, such as
                security or support and maintenance advices
              </li>
              <li>to engage with or contact inactive users of Hurix</li>
              <li>
                to direct certain content and advertisements to you so that you
                are more likely to see content and advertisements that are
                relevant to you
              </li>
              <li>to analyze the data submitted by you</li>
              <li>
                to send offers and promotional materials related to Hurix and
                those of third parties for marketing and other purposes.
              </li>
              <li>
                The Company may also use and share aggregated or de-identified
                information for any purpose and in any manner. This anonymous
                data the Company shares may include non-personally identifiable
                data that the Company creates using your personal information by
                excluding information that makes the data personally
                identifiable.
              </li>
            </ul>
          </div>
          <div>
            <h5>HOW THE COMPANY SHARES YOUR INFORMATION</h5>
            <p>
              The Company may share information as per the terms of this Privacy
              Policy, however the Company shall endeavor that such use of
              information does not create hindrance on your use of Hurix. The
              Company does not share your personal information with third
              parties other than as follows:
            </p>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Others working for the Company. </u>
              </h6>
              <p className="d-inline">
                The Company uses certain trusted third parties to help the
                Company provide, improve, protect, and promote Hurix (such as
                third-party analytics tools to help the Company measure traffic
                and usage trends for Hurix). These third parties will access
                your information only to perform tasks on the Company’s behalf
                and in compliance with this Privacy Policy.
              </p>
            </div>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Social Media. </u>
              </h6>
              <p className="d-inline">
                You may access third-party social media platforms through your
                Hurix account or allow the Company to share data with
                third-party social media platforms, for example, by linking your
                Hurix account with a third-party social media platform or by
                sending/sharing status updates or posts to/on your third-party
                social media platform account. Any data shared with third-party
                social media platforms will be governed by such third-party
                social media platforms’ privacy policy.
              </p>
            </div>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Third Parties. </u>
              </h6>
              <p className="d-inline">
                The Company may also share certain information such as cookie
                data with third-party advertising partners. This information
                would allow third-party ad networks to, among other things,
                deliver targeted advertisements that they believe will be of
                most interest to you.
              </p>
            </div>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Generally with your Consent. </u>
              </h6>
              <p className="d-inline">
                Any information or content that you voluntarily disclose for
                posting on Hurix may become available to the public, as
                controlled by any applicable privacy settings that you set. To
                change your privacy settings on Hurix, you may change your
                profile setting. Once you have shared the content/data or made
                it public, that content/data may be re-shared by others.
              </p>
            </div>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Enforcing Rights. </u>
              </h6>
              <p className="d-inline">
                The Company may also disclose personal information to enforce
                its policies, respond to claims that a posting or other content
                violates others’ rights, or protects anyone’s rights, property
                or safety.
              </p>
            </div>
            <div className="mt-2">
              <h6 className="d-inline">
                <u>Law & Order. </u>
              </h6>
              <p className="d-inline">
                The Company may disclose your information to third parties if it
                determines that such disclosure is reasonably necessary to: (a)
                comply with the laws; (b) protect any person from death or
                serious bodily injury; (c) prevent fraud or abuse of its name,
                brands, trademarks or such other rights belonging to it or its
                other users; or (d) protect its rights.
              </p>
            </div>
          </div>
          <div>
            <p>
              Stewardship of your data is critical to the Company and a
              responsibility that the Company embraces. The Company believes
              that its users’ data should receive the same legal protections
              regardless of whether it’s stored on its servers or on your home
              computer systems or devices. The Company will abide by the
              following principles when receiving, scrutinizing and responding
              to government requests for its users’ data:
            </p>
          </div>
          <div>
            <ul>
              <li>Be transparent</li>
              <li>Fight blanket requests</li>
              <li>Protect all users</li>
              <li>Provide trusted services</li>
            </ul>
          </div>
          <div>
            <h5>STORING OF INFORMATION </h5>
            <div>
              <h6 className="d-inline">
                <u>Retention. </u>
              </h6>
              <p className="d-inline">
                The Company will retain your personal information for as long as
                it needs it.
              </p>
            </div>
            <div>
              <h6 className="d-inline">
                <u>No warranty. </u>
              </h6>
              <p className="d-inline">
                The Company uses commercially reasonable safeguards to help keep
                the information collected through Hurix secure and take
                reasonable steps (such as requesting a unique password) to
                verify your identity before granting you access to your account.
                However, no method of transmission over the internet, or method
                of electronic storage, is 100% secure and so the Company cannot
                fully ensure or guarantee the security of any information you
                transmit to the Company or guarantee that information on Hurix
                may not be accessed, disclosed, altered, or destroyed by any
                person.
              </p>
            </div>
            <div>
              <h6 className="d-inline">
                <u>Around the world. </u>
              </h6>
              <p className="d-inline">
                The Company may store, process and transmit information in
                locations around the world - including those outside your
                country. Information may also be stored locally on the devices
                you use to access Hurix. By registering for and using Hurix, you
                consent to the transfer of information to any part of the world
                in which the Company, its affiliates or service providers
                maintain facilities and the use and disclosure of information
                about you thereto as described in this Privacy Policy.
              </p>
            </div>
          </div>
          <div className="mt-3">
            <h5>CHANGES TO YOUR INFORMATION</h5>
            <p>
              You may change certain of your personal information by editing
              your user account or by sending the Company an e-mail at [•insert
              Email ID]. You are responsible for maintaining the secrecy of your
              unique password and account information, and for controlling
              access to emails between you and the Company, at all times. The
              Company is not responsible for any third party functionality,
              privacy or security policies which you are bound by. Please do
              your part to help the Company.
            </p>
          </div>
          <div className="mt-3">
            <h5>CHANGES</h5>
            <p>
              The Company may share some or all of your information in
              connection with or during negotiation of any merger, financing,
              acquisition or dissolution, collaboration, transaction or
              proceeding involving sale, transfer, divestiture, or disclosure of
              all or a portion of its business or assets. In the event of an
              insolvency, bankruptcy, or receivership, your information may also
              be transferred as a business asset. If another entity acquires the
              Company or its business or assets, that entity will possess all
              your information collected by the Company and will assume the
              rights and obligations regarding your information as described in
              this Privacy Policy.
            </p>
            <p>
              The Company may change this Privacy Policy from time to time. If
              the Company makes any changes to this Privacy Policy, the last
              modified Privacy Policy shall be applicable to you.
            </p>
          </div>
          <div className="mt-3">
            <h5>COMMUNICATIONS</h5>
            <p>
              The Company may periodically send you free newsletters and
              promotional communications. When you receive newsletters or
              promotional communications from the Company, you may “opt-out” of
              these emails by following the unsubscribe instructions provided in
              the email you receive or by contacting the Company at [●insert
              Email ID]. Despite your indicated email preferences, the Company
              may send you notices of any updates to its Privacy Policy, Terms
              and Conditions or other administrative emails.
            </p>
          </div>
          <div className="mt-3">
            <h5>CONTACT</h5>
            <p>
              The Company welcomes your comments or questions regarding this
              Privacy Policy. Please e-mail the Company at [●insert email ID] or
              contact the Company at the following address:
            </p>
            <div>
              <p>[●insert name of the Company]</p>
              <p>Attn: Privacy Policy</p>
              <p>[●insert address and communication details]</p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
